/**
 * @file Import FA Icons and register them for their components
 */

import { library } from '@fortawesome/fontawesome-svg-core'

// Outline/Solid versions (need to be declared as a different name)
// import { 
//   faEnvelope as farEnvelope,
//   // faFile as farFile,
// } from '@fortawesome/free-regular-svg-icons';

// import { 
//   faFacebookF,
//   faInstagram,
// } from '@fortawesome/free-brands-svg-icons';
// import { faEnvelope as fasEnvelope, } from '@fortawesome/free-solid-svg-icons';

import { 
  // faPhone,
  // faCheck,
  // faCircleCheck,
  // faEnvelope,
  // faChartColumn,
  // faPaste,
  // faTruck,
  // faChessQueen,
  // faFile,
  // faFileContract,
  // faCircleChevronLeft,
  // faFileCircleCheck,
  // faDiagramProject,
  // faHome,
  // faQuestion,
  // faStar,
  // faCog,
  // faDownload,
  // faListOl,
  // faList,
  // faBell,
  // faCircleQuestion,
  // faCircleExclamation,
  // faTriangleExclamation,
  // faSun,
  // faMoon,
  faEllipsis,
  faXmark,
  // faCircleXmark,
  // faMagnifyingGlass,
  // faCaretDown,
  // faCaretUp,
  // faChevronDown,
  // faChevronUp,
  // faChevronLeft,
  // faChevronRight,
  // faAngleRight,
  // faAngleDoubleRight,
  // faAngleLeft,
  // faAngleDoubleLeft,
  // faPencil,
  // faTruckFast,
  // faFilter,
  // faBoxesStacked,
  faGrip,
  faArrowUpRightFromSquare,
  // faIdCard,
  // faCrown,
  // faUserGroup,
  // faUser,
  // faClipboard,
  // faFileInvoice,
  // faImage,
  faGripLinesVertical,
  // faTableColumns,
  faPlus,
  faMinus,
  // faLock,
  // faUnlock,
  // faScaleBalanced,
  faCircleInfo,
  // faMapLocation,
  // faNoteSticky,
  // faExpand,
  // faMaximize,
} from '@fortawesome/free-solid-svg-icons';

library.add(
  // faPhone,
  // faCheck,
  // faCircleCheck,
  // farEnvelope,
  // fasEnvelope,
  // faChartColumn,
  // faPaste,
  // faTruck,
  // faChessQueen,
  // faFile,
  // farFile,
  // faFileContract,
  // faCircleChevronLeft,
  // faFileCircleCheck,
  // faDiagramProject,
  // faHome,
  // faQuestion,
  // faStar,
  // faCog,
  // faDownload,
  // faListOl,
  // faList,
  // faBell,
  // faCircleQuestion,
  // faCircleExclamation,
  // faTriangleExclamation,
  // faSun,
  // faMoon,
  faEllipsis,
  // fasStar,
  // farStar,
  faXmark,
  // faCircleXmark,
  // faMagnifyingGlass,
  // faCaretDown,
  // faCaretUp,
  // faChevronDown,
  // faChevronUp,
  // faChevronLeft,
  // faChevronRight,
  // faAngleRight,
  // faAngleDoubleRight,
  // faAngleLeft,
  // faAngleDoubleLeft,
  // faPencil,
  // faTruckFast,
  // faFilter,
  // faBoxesStacked,
  faGrip,
  faArrowUpRightFromSquare,
  // faIdCard,
  // faCrown,
  // faUserGroup,
  // faUser,
  // faClipboard,
  // faFileInvoice,
  // faImage,
  faGripLinesVertical,
  // faTableColumns,
  faPlus,
  faMinus,
  // faLock,
  // faUnlock,
  // faScaleBalanced,
  faCircleInfo,
  // faMapLocation,
  // faNoteSticky,
  // faExpand,
  // faMaximize,
  // faFacebookF,
  // faInstagram
);